// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Address is the predicate function for address builders.
type Address func(*sql.Selector)

// Cart is the predicate function for cart builders.
type Cart func(*sql.Selector)

// CartItem is the predicate function for cartitem builders.
type CartItem func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// OrderItem is the predicate function for orderitem builders.
type OrderItem func(*sql.Selector)

// Payment is the predicate function for payment builders.
type Payment func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// Review is the predicate function for review builders.
type Review func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
